### ISSUE TITLE
How to get podCIDR to show up in the node spec?

### ISSUE THREAD

**Issue by eddiewang** [gravitational/planet#698]
Hi there,

One of my kubernetes applications (https://github.com/squat/kilo/issues/62) requires the podCIDR field to be added to the node spec. The Pod CIDR allocation is turned on in the controller-manager by default on most kubernetes distributions. This is enabled via --allocate-node-cidrs https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/#options

I was wondering if it was possible to expose that via my Gravity install?

Thanks

**Comment by wadells** [comment]
Hi Eddie!

We try to keep the github issue tracker focused on features/bugs.  I'd recommend using our community forums (https://community.gravitational.com/) or community slack (https://grv8.slack.com) for questions similar to this, and file a issue once you are certain there is something actionable.  If you'd like to continue the discussion, try one of those channels.

It looks like the way to turn this off currently is with the "PLANET_DISABLE_FLANNEL" env variable.

https://github.com/gravitational/planet/blob/da6d238905b02303d394f39fba1ff4bf221fa563/tool/planet/start.go#L830-L838

Interestingly, we declare `--allocate-node-cidrs` twice:

https://github.com/gravitational/planet/blob/e12a100d4b901b54bd5d4224bd8fa859a827ac67/build.assets/makefiles/master/k8s-master/kube-controller-manager.service#L22

https://github.com/gravitational/planet/blob/e12a100d4b901b54bd5d4224bd8fa859a827ac67/build.assets/makefiles/master/k8s-master/kube-controller-manager.service#L17

This definitely seems like a mistake and I'm not sure what the expected behavior is when the flag is declared twice.
